%% SPDX-License-Identifier: AGPL-3.0-or-later

-ifndef(TIMEOUT_CONFIG_HRL).
-define(TIMEOUT_CONFIG_HRL, true).

-define(RELOAD_TIMEOUT, 10000).
-define(STATS_TIMEOUT, 1000).
-define(RPC_TIMEOUT, 15000).
-define(GUILD_CALL_TIMEOUT, 10000).
-define(SESSION_CALL_TIMEOUT, 5000).
-define(SHUTDOWN_TIMEOUT, 10000).
-define(DEFAULT_GEN_SERVER_TIMEOUT, 5000).

-endif.
