[workspace]
members = [
	"voxr_admin",
	"voxr_app_proxy",
	"voxr_common",
	"voxr_media_proxy",
	"voxr_gifs",
	"voxr_svc",
	"voxr_messages",
	"voxr_snowflakes",
	"tools/ci",
	"tools/content/update-frozen-snapshot",
	"tools/dev",
	"tools/i18n_auto",
	"voxr_users",
	"voxr_unfurl",
	"packages/markdown_parser/rust",
]
exclude = [
	"voxr_marketing",
	"packages/markdown_parser/rust/fuzz",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
