[package]
name = "push_markdown_plaintext_nif"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
voxr_markdown_parser = { path = "../../../packages/markdown_parser/rust" }
rustler = "0.38.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
