[package]
name = "voxr_win_process_loopback"
version = "0.0.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[workspace]
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
voxr_desktop_native = {path = "../rust"}
voxr_rt_thread = {path = "../rt-thread"}
voxr_screen_frame_bus = {path = "../screen-frame-bus"}
napi = {version = "3.9.1", default-features = false, features = ["dyn-symbols", "napi8"]}
napi-derive = "3.5.6"

[target.'cfg(target_os = "windows")'.dependencies]
windows = {version = "0.62.2", features = [
	"Win32_Foundation",
	"Win32_Media_Audio",
	"Win32_Media_KernelStreaming",
	"Win32_Media_Multimedia",
	"Win32_Security",
	"Win32_Storage_FileSystem",
	"Win32_System_Com",
	"Win32_System_Com_StructuredStorage",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Performance",
	"Win32_System_Threading",
	"Win32_System_Variant",
	"Win32_UI_WindowsAndMessaging",
]}
windows-core = "0.62.2"

[build-dependencies]
napi-build = "2.3.2"
