# SPDX-License-Identifier: AGPL-3.0-or-later
name: Dispatch Dart SDK Regeneration

on:
  push:
    branches:
      - main
    paths:
      - voxr_api/src/api/openapi/openapi.json

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dispatch:
    name: Dispatch regeneration
    if: github.repository == 'voxrapp/voxr'
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: create-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          client-id: ${{ vars.VOXR_CI_APP_ID }}
          private-key: ${{ secrets.VOXR_CI_APP_KEY }}
          owner: voxrapp
          repositories: dart_sdk
          permission-contents: write

      - name: Dispatch Dart SDK regeneration
        env:
          GH_TOKEN: ${{ steps.create-token.outputs.token }}
        run: |
          gh api --method POST repos/voxrapp/dart_sdk/dispatches \
            --field event_type=voxr-openapi-updated
