name: Triage pull request
on:
  pull_request_target:
permissions: {}
jobs:
  label:
    name: Label
    if: github.repository == 'voxrapp/voxr'
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: create-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          client-id: ${{ vars.VOXR_CI_APP_ID }}
          private-key: ${{ secrets.VOXR_CI_APP_KEY }}
          owner: voxrapp
          repositories: voxr
          permission-pull-requests: write

      - name: Label pull request
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
        with:
          repo-token: ${{ steps.create-token.outputs.token }}
          configuration-path: .github/labeller.yaml
          sync-labels: true
